app:
  id: BONADE-UAAC
  version: 1.0.0
apollo:
  bootstrap:
    enabled: true
    namespaces: application
    eagerLoad.enabled: true

server:
  port: ${serverPort:8080}

eureka:
  client:
    service-url:
      defaultZone: ${registryAddr}

# region Config registered to Spring Boot Starter Context
spring:
  profiles:
    active: ${profiles}
  application:
    name: ${app.id}
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 25MB
      location: ${java.io.tmpdir}

  #Datasource
  datasource:
    url: ${db.url}
    username: ${db.username}
    password: ${db.password}
    driver-class-name: ${db.driverClass}
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      connection-timeout: ${db.connectionTimeout}
      minimum-idle: ${db.minIdle}
      maximum-pool-size: ${db.maxActive}
      idle-timeout: ${db.idleTimeout}

  # REDIS
  redis:
    host: ${redis.host}
    port: ${redis.port}
    database: ${redis.database}
    password: ${redis.password}
    timeout: ${redis.timeout}
    lettuce:
      pool:
        max-active: ${redis.lettuce.pool.max-active}
        max-wait: ${redis.lettuce.pool.max-wait}
        max-idle: ${redis.lettuce.pool.max-idle}
        min-idle: ${redis.lettuce.pool.min-idle}

  # KAFKA
  kafka:
    bootstrap-servers: ${kafkaServer}
    producer:
      retries: 0
    #      batch-size: 16384
    #      buffer-memory: 33554432
    #      properties:
    #        linger.ms: 1
    consumer:
      enable-auto-commit: true
      auto-commit-interval: 100ms
      group-id: ${app.id}-Group

  # RabbitMQ
  rabbitmq:
    host: ${rabbitmq.host}
    port: ${rabbitmq.port}
    username: ${rabbitmq.username}
    password: ${rabbitmq.password}
    platform:
      host: ${rabbitmq.platform.host}
      port: ${rabbitmq.platform.port}
      username: ${rabbitmq.platform.username}
      password: ${rabbitmq.platform.password}

  # flow - ZT
  flow:
    client:
      #客户端ID
      clientId: ${flow.client.clientId}
      #客户端密码
      secret: ${flow.client.secret}
    server:
      host: ${flow.server.host}
      gateway: ${flow.server.gateway}
    #MQ地址(中台)
    rabbitmq:
      host: ${flow.rabbitmq.host}
      port: ${flow.rabbitmq.port}
      username: ${flow.rabbitmq.username}
      password: ${flow.rabbitmq.password}

  # Sleuth & Zipkin
  sleuth:
    enabled: false
    sampler:
      probability: 1.0
  zipkin:
    enabled: false
    sender:
      type: KAFKA
    kafka:
      topic: zipkin

  cloud:
    # Sentinel
    sentinel:
      enabled: ${sentinelEnable:true}
      eager: ${sentinelEager:true}
      transport:
        port: ${sentinelPort:8719}
        dashboard: ${sentinelDashboard:}

  cache:
    type: generic
# endregion

mybatis-plus:
  mapper-locations: classpath:/mapper/**/*Mapper.xml
  type-aliases-package: com.bonade.uaac.domain.entity
  type-enums-package: com.bonade.uaac.domain.enums
  global-config:
    banner: false
    db-config:
      id-type: ID_WORKER
      table-underline: true
      logic-delete-value: 0
      logic-not-delete-value: 1
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    jdbc-type-for-null: NULL

jasypt:
  encryptor:
    password: ${encrypt.key}

# region Actuator config
info:
  version: ${app.version}
  commonStarterVersion: 2.2.36-SNAPSHOT
  jobExecutorVersion: UNABLE

management:
  endpoints:
    web:
      exposure:
        #加载所有的端点，默认只加载了info、health
        include: '*'
  endpoint:
    health:
      show-details: always
    #可以关闭指定的端点
    shutdown:
      enabled: false
# endregion

swagger2:
  enable: ${swaggerEnable}
  base-package: com.bonade.uaac
  title: 用户认证/授权中心 API
  contact-name: 安徽研发中心
  contact-url:
  contact-email:
  description: API 接口文档

j2cache:
  openSpringCache: true
  redisClient: lettuce
  config-location: j2cache.properties

#uaac:
#  wechat:
#    weapp:
#      visitor:
#        appId: wx9fce116054c96065
#        appSecret: 55d7a0e94e9fee99aaffa0fc1b15d278
feign:
  sentinel:
    enabled: true
